### ISSUE TITLE
Using official LLVM binaries on windows? 

### ISSUE THREAD

**Issue by Krovatkin** [igor84/summus#1]
Hey there!

I think you've hit the nail on the head with this idea! LLVM **really** needs more self-contained coherent examples to help devs to ramp up quickly. I have a quick question, though.

Is there a particular reason why you are **not** using official binaries on windows? It would be really nice if we could switch to the official builds! Frankly, **Clang compiler for Windows (LLVM-3.9.0svn-r258602-win64.exe)** looks a bit **shady**.

**Comment by igor84** [comment]
Hi,

Thanks. I also felt that existing LLVM tutorials are lacking in this area and hoped my project will be a meaningful contribution to learning about LLVM usage besides learning about compiler frontends.

I didn't use official build because it was on version 3.8 when I started. I tried installing 3.9.1 from [here](http://releases.llvm.org/download.html) now but it is not as straightforward as this unofficial build. I installed Clang for Windows (64bit) but saw that include/llvm-c/ only contains lto.h file and no Core.h and other files. I then downloaded LLVM source code and extracted include/llvm and include/llvm-c from there but I am still getting an error "Cannot open include file: 'llvm/Support/DataTypes.h': No such file or directory". There is no llc command in the installation and for beginners it is very useful to run:
```
clang -S -emit-llvm test.cpp -o test.ll 
llc -march=cpp test.ll -o llvmtest.cpp
```
to see what kind of LLVM is generated for some code. Although I selected the option to add LLVM to system path during installation that did not happen.

All of this just works with unofficial build. Since this project is meant for beginners I want them to be able to very quickly and easily setup everything needed for playing with the project. With all these issues I feel the best I can do is mention that users can try official build but say that if they just want everything to work right after installation to use the unofficial one.

... Unless you can somehow help me make using official build as easy to setup?

**Comment by Krovatkin** [comment]
I could give it a try. Unfortunately, I'm one of those beginners you did this project for :-) so I'm not really hopeful I can get it to work. I'll report back in a bit.

**Comment by Krovatkin** [comment]
@igor84 I ran into the exact issue you mentioned w/ pre-built binaries; they only ship **lto.h**. So I downloaded the source code and checked **include** directory for the missing headers. Unfortunately, the headers your compiler requires need to be *configured/built* with `cmake`.  So now I'm building the entire llvm and down the rabbit hole we go :-)

**Comment by igor84** [comment]
I though something like that will be needed. Personally I never worked with make files of any kind but always had this strong feeling it is just wrong that they are needed at all. Don't even have CMake installed. Anyway if you succeed and send me the instructions I will include them in readme. Thanks for helping.

**Comment by Krovatkin** [comment]
I'll write up instructions sometime over the weekend. It's not particularly complicated, but I'll have more time over the weekend.
